# Generated by Django 5.2.7 on 2025-10-11 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Brief title describing the item (e.g., 'Black iPhone 13')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('item_type', models.CharField(choices=[('lost', 'Lost Item'), ('found', 'Found Item')], help_text='Is this a lost or found item?', max_length=10)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents & IDs'), ('clothing', 'Clothing & Accessories'), ('books', 'Books & Stationery'), ('keys', 'Keys & Cards'), ('bags', 'Bags & Backpacks'), ('sports', 'Sports Equipment'), ('jewelry', 'Jewelry & Watches'), ('other', 'Other')], default='other', help_text='Category of the item', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the item (optional but recommended)', null=True, upload_to='items/%Y/%m/%d/')),
                ('location', models.CharField(help_text="Where was the item lost/found? (e.g., 'Library 2nd Floor', 'Cafeteria')", max_length=200)),
                ('date_lost_found', models.DateField(default=django.utils.timezone.now, help_text='When was the item lost/found?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('closed', 'Closed')], default='active', help_text='Current status of the item', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before item is publicly visible')),
                ('contact_phone', models.CharField(blank=True, help_text='Optional contact phone number', max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text="Optional contact email (defaults to user's email)", max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was posted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('reward_offered', models.BooleanField(default=False, help_text='Is a reward being offered for this item?')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount (if applicable)', max_digits=10, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times this item has been viewed')),
                ('user', models.ForeignKey(help_text='User who posted this item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional image for the item', upload_to='items/additional/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='items.item')),
            ],
            options={
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type', 'is_approved'], name='items_item_item_ty_e66521_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_item_categor_db7f55_idx'),
        ),
    ]
