# Generated by Django 5.2.4 on 2025-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin must approve before item is publicly visible'),
        ),
    ]
